name: Release BankManagementSystem

on:
  workflow_dispatch:  # Allows the workflow to be triggered manually

permissions:
  contents: write  # Grant the workflow permission to push to the repository

jobs:
  Versioning:
    uses: ./.github/workflows/service-versioning.yml
    with:
      project_file_path: "Course2/BankManagementSystem.API/BankManagementSystem.API.csproj"
      should_add_version_tag: ${{ github.ref == 'refs/heads/main' }}
   
#  Release:
#    needs: Versioning
#    uses: ./.github/workflows/build-and-push-nuget-package.yml
#    with:
#      project_file_path: 'src/EventStorage/EventStorage.csproj'
#      version: ${{ needs.Versioning.outputs.version }}
#      package_name: 'Mirolim.EventStorage'
#      application_name: 'EventStorage'
#    secrets:
#      nuget_org_api_key: ${{ secrets.EVENT_STORAGE_NUGET_ORG_API_KEY }}
#      github_nuget_source_secret: ${{ secrets.NUGET_SOURCE_SECRET }}