name: Release BankManagementSystem

on:
  workflow_dispatch:  # Allows the workflow to be triggered manually

permissions:
  contents: write  # Grant the workflow permission to push to the repository

jobs:
#  Versioning:
##    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/production'
#    uses: ./.github/workflows/service-versioning.yml
#    with:
#      project_file_path: "Course2/BankManagementSystem.API/BankManagementSystem.API.csproj"
#      should_add_version_tag: ${{ github.ref == 'refs/heads/main' }}
   
  Release:
#    needs: Versioning
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore Course2/Course2.sln

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build, tags, and push images to DockerHub
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: true
        with:
          context: Course2/
          file: Course2/BankManagementSystem.API/Dockerfile
          push: true
          tags: |
            mirolimmajidov/itrun.cbs:latest
#            mirolimmajidov/itrun.cbs:${{ needs.Versioning.outputs.version }}