name: Running all tests

on:
  pull_request:
    branches: [ main ]
    paths:
      - src/Course2/Tests/**
      - .github/workflows/run-tests.yml
  workflow_dispatch:

jobs:
  services:
    sqlserver:
      image: mcr.microsoft.com/mssql/server:2022-latest
      env:
        SA_PASSWORD: '12345678!'
        ACCEPT_EULA: "Y"
      options: >-
        --health-cmd "exit 0"
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5
      ports:
        - 1433:1433

  Testing:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore Course2/Course2.sln

      - name: Run unit and functionality tests
        run: dotnet test 'Tests/Examples/UnitTesting.NTest/CalculatorApp.UnitTesting.NUnitTest.csproj' --logger "console;verbosity=detailed" --blame

      - name: Run integration tests
        env:
          ConnectionStrings__DefaultConnection: "Server=localhost,1433;Database=${{ inputs.database_name }};User Id=sa;Password=12345678!;TrustServerCertificate=True;"
        run: dotnet test 'Tests/BankManagementSystem.xUNit.IntegrationTests/BankManagementSystem.xUNit.IntegrationTests.csproj' --logger "console;verbosity=detailed" --blame